import ResponsiveImage from '@/components/responsive-image';
import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { BrandHeader, BrandFooter } from '@/components/brand-shell-v2';
import { lines } from '@/lib/catalog';

export const metadata: Metadata = { title:'Sobre a marca e as quatro linhas', description:'Conheça a Vektua XYZ: objetos com personalidade para escolher, celebrar, personalizar e descobrir, com quatro linhas em uma só marca.', robots:{index:false,follow:false} };
export default function SobrePage(){return <><BrandHeader/><main id="conteudo" tabIndex={-1}><div className="container page-space"><nav className="breadcrumbs" aria-label="Localização"><Link href="/">Início</Link><span aria-current="page">Sobre a Vektua XYZ</span></nav><section className="about-grid"><div><h1>Uma ideia encontra<br/>o mundo.</h1><p className="lead">Objetos com personalidade. Do achado à peça só sua.</p><p>Vektua expressa, na narrativa da marca, o projeto que ganha forma como objeto. XYZ faz referência aos três eixos do espaço tridimensional — não ao número de linhas comerciais.</p><p>Reunimos quatro motivos de escolha sob uma única identidade: design, ocasião, referência pessoal e a descoberta de um acessório que combine com o contexto.</p><p>A impressão 3D é o meio de fabricação, não a promessa de produzir qualquer coisa. Produtos, direitos, medidas, prazos e condições serão comunicados apenas quando verificados.</p><Link className="button" href="/busca">Explorar o catálogo<ArrowUpRight size={18} aria-hidden="true"/></Link></div><div className="about-image"><ResponsiveImage src="/images/products/remix/G-VAS-ESC-01_REMIX.webp" alt="Ambientação REMIX editada do SKU G-VAS-ESC-01; peça física não verificada" width="800" height="900"/><span className="concept-label">Imagem REMIX · ambientação editada</span></div></section><section className="lines-section" aria-labelledby="about-lines"><div className="section-heading"><h2 id="about-lines">Quatro caminhos para encontrar a sua peça.</h2><p>Uma marca, quatro linhas comerciais independentes.</p></div><div className="line-grid vx-line-grid">{lines.map(line=><Link key={line.id} href={line.path} className={`line-card line-${line.id}`}><div className="line-image"><ResponsiveImage src={line.image} width="600" height="420" loading="lazy" alt={`Imagem ${line.id === "feitos" ? "conceitual" : "REMIX ambientada"} da linha ${line.name}; peça física não verificada`}/><span className="concept-label">{line.id === "feitos" ? "Imagem conceitual" : "Imagem REMIX · ambientação editada"}</span></div><div className="line-card-text"><h3>{line.name}<ArrowUpRight size={19} aria-hidden="true"/></h3><p>{line.description}</p></div></Link>)}</div></section><section className="vx-about-disclaimer"><h2>A experiência ainda está em construção.</h2><p>Esta versão é um protótipo demonstrativo. A linha Chaveiros contempla uma proposta de distribuição em estabelecimentos locais, mas não existem parceiros ou pontos ativos confirmados aqui. Nenhum produto está liberado para compra neste site.</p><Link href="/ajuda" className="text-link">Leia as perguntas frequentes<ArrowUpRight size={17} aria-hidden="true"/></Link></section></div></main><BrandFooter/></>}
