'use client';
import { useState, type ReactNode } from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { ArrowRight, ArrowUpRight, ShoppingBag, Search, Minus, Plus, Trash2, MessageCircle, CheckCircle2 } from 'lucide-react';
import ResponsiveImage from '@/components/responsive-image';
import { BrandHeader, BrandFooter } from '@/components/brand-shell-v2';
import { useCart } from '@/components/cart-context';
import { commercialLines, commercialProducts, getCommercialProduct, searchableProducts, type CommercialProduct } from '@/lib/commercial-catalog';
import { buildWhatsAppOrderUrl } from '@/lib/whatsapp-order';
import { WHATSAPP_URL } from '@/lib/whatsapp';
import type { Line } from '@/lib/catalog';

function ButtonLink({ href, children, secondary = false }: { href:string;children:ReactNode;secondary?:boolean }) {
  return <Link className={`button ${secondary?'secondary':''}`} href={href}>{children}<ArrowUpRight size={17} aria-hidden="true"/></Link>;
}
function Picture({product,large=false}:{product:CommercialProduct;large?:boolean}) {
  return product.image ? <div className={large?'pdp-image':'product-picture'}><ResponsiveImage src={product.image} alt={`Imagem REMIX ambientada e editada do produto ${product.name}`} width={large?900:640} height={large?900:640} loading={large?'eager':'lazy'} style={{objectFit:'contain'}}/><span className="concept-label">Imagem REMIX · ambientação editada</span></div>
    : <div className={`vx-photo-pending ${large?'vx-photo-large':''}`} role="img" aria-label={`Imagem comercial REMIX ainda não disponível para ${product.name}`}><ShoppingBag size={30} aria-hidden="true"/><span>Imagem REMIX em preparação</span><small>{product.id}</small></div>;
}
function Card({product}:{product:CommercialProduct}) {
  return <article className="product-card"><Link className="vx-card-link" href={`/produto/${product.slug}`} aria-label={`Ver ${product.name}`}><Picture product={product}/></Link><div className="product-info"><span className="product-category">{commercialLines.find(l=>l.id===product.line)?.name}</span><Link className="product-name" href={`/produto/${product.slug}`}>{product.name}</Link><div className="vx-price-status">Preço e disponibilidade: consultar</div><Link className="text-link" href={`/produto/${product.slug}`}>Ver produto <ArrowUpRight size={15}/></Link></div></article>;
}
function Breadcrumb({label,back='/'}:{label:string;back?:string}) {return <nav className="breadcrumbs" aria-label="Localização"><Link href={back}>Início</Link><span><span aria-hidden="true">/</span><span aria-current="page">{label}</span></span></nav>;}
function Home(){
 const [line,setLine]=useState<Line|'todas'>('todas');
 const featured=line==='todas'?[commercialProducts.find(p=>p.id==='G-ORG-RC-01'),commercialProducts.find(p=>p.id==='S-HAL-DEC-01'),commercialProducts.find(p=>p.id==='CAN-PET-001'),commercialProducts.find(p=>p.id==='G-CHV-JJ-01')].filter((p):p is CommercialProduct=>!!p):commercialProducts.filter(p=>p.line===line).slice(0,8);
 return <><section className="hero container vx-hero"><div className="hero-copy"><h1>Objetos com<br/><span>personalidade.</span></h1><p>Objetos, coleções, miniaturas personalizadas e chaveiros. Escolha suas peças e envie sua solicitação pelo WhatsApp.</p><div className="hero-buttons"><ButtonLink href="/busca">Explorar o catálogo</ButtonLink><ButtonLink href="/chaveiros" secondary>Conhecer chaveiros</ButtonLink></div><p className="small-note">Sem pagamento pelo site. A equipe confirma preço, estoque e prazo antes de fechar o pedido.</p></div><div className="hero-image"><ResponsiveImage src="/images/products/remix/G-VAS-ESC-01_REMIX.webp" alt="Imagem REMIX ambientada e editada do cachepô escultórico" width={1536} height={1024} fetchPriority="high"/><span className="hero-caption">Do achado à peça só sua.</span><span className="concept-label">Imagem REMIX · ambientação editada</span></div></section>
 <section className="lines-section container"><div className="section-heading"><h2>Quatro linhas. Uma marca.</h2><p>Encontre a peça pelo design, ocasião, personalização ou estilo.</p></div><div className="line-grid vx-line-grid">{commercialLines.map(l=><Link href={l.path} key={l.id} className={`line-card line-${l.id}`}><div className="line-image"><ResponsiveImage src={l.image} alt={`Visual da linha ${l.name}${l.id==='feitos'?' · ilustração conceitual':' · imagem REMIX editada'}`} width={600} height={420} loading="lazy"/></div><div className="line-card-text"><h3>{l.name}<ArrowUpRight size={18}/></h3><p>{l.verb}</p></div></Link>)}</div></section>
 <section className="catalog-section container"><div className="section-heading heading-link"><div><h2>Escolha seus próximos achados.</h2><p>Explore nossos produtos e encontre a peça que combina com você.</p></div><Link href="/busca" className="text-link">Ver todos os produtos<ArrowRight size={18}/></Link></div><div className="filter-chips" aria-label="Filtrar por linha">{[{id:'todas',name:'Todas'},...commercialLines].map(l=><button type="button" key={l.id} className={line===l.id?'selected':''} aria-pressed={line===l.id} onClick={()=>setLine(l.id as Line|'todas')}>{l.name}</button>)}</div><div className="product-grid vx-products">{featured.map(p=><Card key={p.id} product={p}/>)}</div></section>
 <section className="how-section container"><div className="section-heading"><h2>Como seu pedido funciona</h2></div><div className="how-grid"><div><ShoppingBag/><h3>Escolha</h3><p>Adicione os itens cadastrados ao carrinho e ajuste quantidades.</p></div><div><MessageCircle/><h3>Envie pelo WhatsApp</h3><p>Confira a lista e abra uma mensagem pronta, que você pode editar antes de enviar.</p></div><div><CheckCircle2/><h3>Confirme conosco</h3><p>A equipe confirma valores, disponibilidade e entrega. O site não recebe pagamentos.</p></div></div><ButtonLink href="/como-funciona">Entenda o processo</ButtonLink></section></>;
}
function Catalog({line,collection=false}:{line?:Line;collection?:boolean}){
 const [query,setQuery]=useState('');const [sort,setSort]=useState('default');
 const current=commercialLines.find(l=>l.id===line);let shown=searchableProducts(line,query);
 if(collection) shown=shown.filter(p=>p.collection==='Halloween');
 if(sort==='name')shown=[...shown].sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));
 const title=collection?'Pequenos Encantos':current?.name||'Todos os produtos';
 return <div className="container page-space"><Breadcrumb label={title}/><div className="catalog-intro"><div><h1>{title}</h1><p>{current?.description||'Explore todas as quatro linhas da Vektua XYZ. Os pedidos são encaminhados pelo WhatsApp.'}</p><p className="small-note">Preço, frete, disponibilidade e prazo são confirmados no atendimento. Pagamento online desabilitado.</p></div></div><form className="search-form" onSubmit={e=>e.preventDefault()}><Search size={20}/><input aria-label="Buscar produtos" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busque por nome, tema ou SKU"/></form><div className="listing-controls"><span className="result-count" role="status">{shown.length} {shown.length===1?'produto':'produtos'} encontrados</span><label className="sort-label">Ordenar <select value={sort} onChange={e=>setSort(e.target.value)}><option value="default">Catálogo</option><option value="name">Nome A–Z</option></select></label></div>{shown.length?<div className="product-grid catalog-grid">{shown.map(p=><Card key={p.id} product={p}/>)}</div>:<div className="empty-state"><h2>Nenhum produto encontrado.</h2><button className="button" type="button" onClick={()=>setQuery('')}>Limpar busca</button></div>}</div>;
}
function ProductDetail({product}:{product:CommercialProduct}){
 const {add}=useCart();const [quantity,setQuantity]=useState(1);const [option,setOption]=useState('A combinar no WhatsApp');const [added,setAdded]=useState(false);
 const line=commercialLines.find(l=>l.id===product.line);
 return <div className="container page-space"><Breadcrumb label={product.name} back={line?.path}/><div className="pdp-grid"><div><Picture product={product} large/>{product.gallery&&product.gallery.length>1&&<div className="gallery-controls">{product.gallery.map((src,i)=><a key={src} href={src} target="_blank" rel="noopener noreferrer" aria-label={`Abrir imagem REMIX ${i+1}`}>Imagem {i+1}</a>)}</div>}<p className="small-note">Imagens REMIX são edições de ambientação. Elementos do cenário não estão incluídos. As variantes são confirmadas no atendimento.</p></div><div className="pdp-copy"><span className="product-category">{line?.name} · SKU {product.id}</span><h1>{product.name}</h1><p className="pdp-description">{product.description}</p><div className="vx-price-status vx-price-large">Preço sob consulta pelo WhatsApp</div><label className="vx-field">Opção, cor ou personalização a consultar<input value={option} maxLength={100} onChange={e=>{setOption(e.target.value);setAdded(false);}} placeholder="Ex.: cor desejada, detalhes da peça"/></label><div className="add-row"><div className="quantity-control" role="group" aria-label="Quantidade"><button type="button" disabled={quantity<=1} onClick={()=>setQuantity(q=>Math.max(1,q-1))} aria-label="Diminuir quantidade"><Minus size={16}/></button><output>{quantity}</output><button type="button" disabled={quantity>=99} onClick={()=>setQuantity(q=>Math.min(99,q+1))} aria-label="Aumentar quantidade"><Plus size={16}/></button></div><button type="button" className="button" disabled={!option.trim()} onClick={()=>{add(product.id,option.trim(),quantity);setAdded(true);}}><ShoppingBag size={18}/>{added?'Adicionar novamente':'Adicionar ao carrinho'}</button></div>{added&&<p role="status"><Link className="text-link" href="/carrinho">Item adicionado. Ver carrinho <ArrowRight size={17}/></Link></p>}<p className="purchase-note">Nenhum pagamento ocorre pelo site. O envio da solicitação pelo WhatsApp não cria uma compra confirmada.</p><div className="vx-detail-notes"><h2>Antes de confirmar</h2><p>Medidas, material, itens incluídos, acabamento, preço, entrega e disponibilidade serão esclarecidos no atendimento.</p>{product.personalized&&<p>Miniaturas são estilizadas, não fotorrealistas. Não envie fotos pessoais pelo site; a necessidade e o modo de envio de referências serão combinados diretamente.</p>}</div></div></div><section className="related-section"><div className="section-heading"><h2>Mais para descobrir</h2></div><div className="product-grid">{commercialProducts.filter(p=>p.id!==product.id&&p.line===product.line).slice(0,4).map(p=><Card key={p.id} product={p}/>)}</div></section></div>;
}
function Cart(){
 const {items,ready,update,clear}=useCart();const [notes,setNotes]=useState('');const url=buildWhatsAppOrderUrl(items,notes);
 return <div className="container page-space"><Breadcrumb label="Carrinho"/><div className="section-heading"><h1>Seu carrinho</h1><p>Confira seus produtos antes de enviar a solicitação. Não há pagamento no site.</p></div>{!ready?<p role="status">Carregando carrinho…</p>:items.length===0?<div className="empty-state"><ShoppingBag size={42}/><h2>Seu carrinho está vazio.</h2><p>Adicione seus produtos favoritos e envie uma única solicitação pelo WhatsApp.</p><ButtonLink href="/busca">Explorar catálogo</ButtonLink></div>:<div className="cart-layout"><div className="cart-items">{items.map(item=>{const p=commercialProducts.find(p=>p.id===item.productId);if(!p)return null;return <article className="cart-item" key={`${p.id}-${item.color}`}><Link href={`/produto/${p.slug}`}>{p.image?<ResponsiveImage src={p.image} alt={`REMIX de ${p.name}`} width={140} height={140}/>:<div className="vx-cart-placeholder">{p.id}</div>}</Link><div className="cart-item-info"><Link href={`/produto/${p.slug}`}><h2>{p.name}</h2></Link><p>SKU: {p.id}</p><p>Opção: {item.color}</p><div className="quantity-control" role="group" aria-label={`Quantidade de ${p.name}`}><button type="button" disabled={item.quantity<=1} aria-label={`Diminuir ${p.name}`} onClick={()=>update(p.id,item.color,item.quantity-1)}><Minus size={16}/></button><output>{item.quantity}</output><button type="button" disabled={item.quantity>=99} aria-label={`Aumentar ${p.name}`} onClick={()=>update(p.id,item.color,item.quantity+1)}><Plus size={16}/></button></div></div><div className="cart-item-end"><button className="icon-button" type="button" onClick={()=>update(p.id,item.color,0)} aria-label={`Remover ${p.name}`}><Trash2 size={18}/></button></div></article>;})}<button className="text-link" type="button" onClick={clear}>Limpar carrinho <Trash2 size={16}/></button></div><aside className="cart-summary"><h2>Enviar solicitação</h2><p>{items.reduce((sum,item)=>sum+item.quantity,0)} unidade(s) · {items.length} seleção(ões)</p><label className="vx-field">Observações opcionais<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={300} rows={4} placeholder="Ex.: preferências de cor ou perguntas sobre entrega"/></label><dl><div><dt>Preço final</dt><dd>A confirmar</dd></div><div><dt>Frete e prazo</dt><dd>A confirmar</dd></div><div><dt>Pagamento</dt><dd>Não realizado aqui</dd></div></dl>{url&&<a className="button vx-whatsapp-checkout" href={url} target="_blank" rel="noopener noreferrer" aria-label="Abrir WhatsApp com lista de produtos do carrinho"><MessageCircle size={19}/>Enviar pedido pelo WhatsApp <ArrowUpRight size={17}/></a>}<p className="small-note">O WhatsApp abrirá uma mensagem editável com SKUs, opções e quantidades. Envie-a para solicitar confirmação da equipe. O carrinho permanece salvo nesta sessão; abrir o aplicativo não confirma o pedido.</p><ButtonLink href="/busca" secondary>Continuar comprando</ButtonLink></aside></div>}</div>;
}
function Info({path}:{path:string}){
 if(path==='/ajuda')return <div className="container page-space narrow-page"><Breadcrumb label="Ajuda"/><h1>Perguntas frequentes</h1><h2>Posso pagar pelo site?</h2><p>Não. Escolha os produtos no carrinho e envie a solicitação pelo WhatsApp. O pagamento, quando aplicável, será combinado fora do site após confirmação das condições.</p><h2>Meu pedido está confirmado quando clico no WhatsApp?</h2><p>Não. É necessário enviar a mensagem e receber confirmação humana de disponibilidade, valores e prazo.</p><h2>Os preços estão definidos?</h2><p>O catálogo não publica preços fictícios. Os valores reais serão informados no atendimento antes de qualquer aceite.</p><h2>As imagens mostram exatamente o produto?</h2><p>Imagens REMIX são composições editadas. Produtos sem REMIX verificado neste site exibem apenas identificação textual.</p><h2>Onde estão os chaveiros?</h2><p>A linha Chaveiros está disponível para consulta digital. Pontos de venda físicos dependem de instalação efetivamente confirmada.</p><ButtonLink href="/contato">Falar com a equipe</ButtonLink></div>;
 if(path==='/contato')return <div className="container page-space narrow-page"><Breadcrumb label="Contato"/><h1>Converse com a Vektua XYZ</h1><p className="lead">Dúvidas, condições de pedidos e propostas para pontos parceiros: nosso canal é o WhatsApp.</p><a className="button" href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer">Abrir WhatsApp <MessageCircle size={18}/></a><p className="small-note">A mensagem sugerida pode ser editada. Nenhuma compra ou parceria é confirmada ao abrir a conversa.</p></div>;
 if(path==='/como-funciona'||path==='/checkout'||path.startsWith('/pedido/'))return <div className="container page-space narrow-page"><Breadcrumb label="Como pedir"/><h1>Escolha, envie, confirme.</h1><ol className="process-list"><li><span>1</span><div><h2>Selecione suas peças</h2><p>Adicione itens e quantidades ao carrinho.</p></div></li><li><span>2</span><div><h2>Envie pelo WhatsApp</h2><p>A lista é preparada automaticamente, mas você decide quando enviar a mensagem.</p></div></li><li><span>3</span><div><h2>Aguarde a confirmação</h2><p>Disponibilidade, preço final, frete, prazo e pagamento são tratados pela equipe antes de qualquer pedido ser confirmado.</p></div></li></ol><ButtonLink href="/carrinho">Ir ao carrinho</ButtonLink></div>;
 if(path==='/sobre')return <div className="container page-space narrow-page"><Breadcrumb label="Sobre"/><h1>Vektua XYZ. Objetos com personalidade.</h1><p className="lead">Uma marca para escolher objetos, celebrar datas, personalizar miniaturas e descobrir chaveiros.</p><p>XYZ representa os três eixos do espaço tridimensional; não é o número de linhas. A impressão 3D é nosso meio de fabricação, não uma promessa de fabricar qualquer projeto.</p><ButtonLink href="/busca">Explorar catálogo</ButtonLink></div>;
 const policy=path.replace('/politicas/','');
 const headings:Record<string,string>={'entrega':'Entrega','trocas-devolucoes':'Trocas e devoluções','privacidade':'Privacidade','termos':'Termos de uso'};
 if(headings[policy])return <div className="container page-space narrow-page"><Breadcrumb label={headings[policy]}/><h1>{headings[policy]}</h1><p className="lead">Informações essenciais para pedidos encaminhados por WhatsApp.</p>{policy==='entrega'?<p>Frete, região atendida, prazo de produção e prazo de transporte serão informados individualmente antes da confirmação do pedido. Não há prazo automático ou estoque reservado pelo carrinho.</p>:policy==='trocas-devolucoes'?<p>Para dúvidas sobre cancelamento, problemas, avarias, trocas ou devoluções, fale pelo WhatsApp. Os direitos legais aplicáveis permanecem preservados; condições detalhadas serão informadas previamente à contratação.</p>:policy==='privacidade'?<p>O carrinho guarda SKUs, opções e quantidades no armazenamento de sessão do navegador. As observações são usadas apenas para preparar a mensagem de WhatsApp quando você clica no botão. O site não recebe pagamentos, cartões ou fotos de referência por este fluxo. Ao abrir o WhatsApp, o tratamento da conversa também segue as condições do aplicativo.</p>:<p>O site apresenta produtos e prepara solicitações. A seleção e o clique no WhatsApp não geram compra, cobrança, reserva, contrato ou pedido confirmado. A equipe comunica condições comerciais antes da confirmação.</p>}<p><a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer" className="text-link">Dúvidas? Fale conosco <ArrowUpRight size={16}/></a></p></div>;
 return <div className="container page-space empty-state"><h1>Página não encontrada.</h1><ButtonLink href="/">Voltar ao início</ButtonLink></div>;
}
export default function CommerceStorefront(){
 const path=(usePathname()||'/').replace(/\/$/,'')||'/';
 let content:ReactNode;
 if(path==='/')content=<Home/>;
 else if(path==='/busca')content=<Catalog/>;
 else if(path==='/objetos-colecionaveis')content=<Catalog line="objetos"/>;
 else if(path==='/datas-colecoes')content=<Catalog line="datas"/>;
 else if(path==='/datas-colecoes/pequenos-encantos')content=<Catalog line="datas" collection/>;
 else if(path==='/feitos-para-voce'||path==='/feitos-para-voce/pet'||path==='/feitos-para-voce/pessoa')content=<Catalog line="feitos"/>;
 else if(path==='/chaveiros')content=<Catalog line="chaveiros"/>;
 else if(path.startsWith('/produto/')){const product=getCommercialProduct(path.slice('/produto/'.length));content=product?<ProductDetail product={product}/>:<Info path={path}/>;}
 else if(path==='/carrinho')content=<Cart/>;
 else content=<Info path={path}/>;
 return <><BrandHeader/><main id="conteudo" tabIndex={-1}>{content}</main><BrandFooter/></>;
}