'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, ArrowUpRight, Box, Menu, Palette, Ruler, Search, ShoppingBag } from 'lucide-react';
import { lines, products, money, type Product } from '@/lib/catalog';
import { useCart } from '@/components/cart-context';

function Logo({ light = false }: { light?: boolean }) {
  return <Link href="/" className={`brand vx-logo ${light ? 'light' : ''}`} aria-label="Vektua XYZ — página inicial"><img src={light ? '/brand/vektua-wordmark-negative.svg' : '/brand/vektua-wordmark.svg'} width="192" height="48" alt="Vektua XYZ" /></Link>;
}
function LinkButton({ href, children, secondary = false }: { href: string; children: React.ReactNode; secondary?: boolean }) {
  return <Link href={href} className={`button ${secondary ? 'secondary' : ''}`}>{children}<ArrowUpRight aria-hidden="true" size={18}/></Link>;
}
function Preview({ children = 'Visualização digital · não é foto de produto físico' }: { children?: React.ReactNode }) {return <span className="concept-label">{children}</span>;}
function Header() {
  const { items } = useCart();
  const quantity = items.reduce((total, item) => total + item.quantity, 0);
  return <><a href="#conteudo" className="skip-link">Pular para o conteúdo</a><div className="demo-strip"><span>Vektua XYZ · Objetos com personalidade</span><span>Protótipo · preços ilustrativos · vendas desabilitadas</span></div>
    <header className="site-header"><div className="header-inner"><Logo/><nav className="desktop-nav" aria-label="Navegação principal">{lines.map(line => <Link key={line.id} href={line.path}>{line.name}</Link>)}</nav>
      <div className="header-actions"><Link href="/busca" className="icon-button" aria-label="Buscar produtos"><Search aria-hidden="true" size={21}/></Link><Link href="/ajuda" className="help-nav">Ajuda</Link><Link href="/carrinho" className="icon-button cart-icon" aria-label={`Carrinho demonstrativo: ${quantity} itens`}><ShoppingBag aria-hidden="true" size={21}/>{quantity > 0 && <span className="cart-count">{quantity}</span>}</Link>
      <details className="vx-mobile-nav"><summary aria-label="Abrir navegação"><Menu aria-hidden="true" size={23}/></summary><nav aria-label="Navegação móvel">{lines.map(line => <Link key={line.id} href={line.path}>{line.name}<ArrowUpRight size={15} aria-hidden="true"/></Link>)}<Link href="/ajuda">Ajuda<ArrowUpRight size={15} aria-hidden="true"/></Link></nav></details></div></div></header></>;
}
function Footer(){return <footer className="site-footer"><div className="footer-main container"><div className="footer-brand"><Logo light/><p>Objetos com personalidade.<br/>Do achado à peça só sua.</p></div><div><h3>Explore</h3>{lines.map(line=><Link key={line.id} href={line.path}>{line.name}</Link>)}</div><div><h3>Conheça</h3><Link href="/sobre">Sobre a Vektua XYZ</Link><Link href="/como-funciona">Como funciona</Link><Link href="/ajuda">Perguntas frequentes</Link><Link href="/contato">Atendimento</Link></div><div><h3>Informações</h3><Link href="/politicas/entrega">Entrega</Link><Link href="/politicas/trocas-devolucoes">Trocas e devoluções</Link><Link href="/politicas/privacidade">Privacidade</Link><Link href="/politicas/termos">Termos de uso</Link></div></div><div className="footer-bottom container"><span>© 2026 Vektua XYZ</span><span>Identidade digital em implementação · sem liberação comercial</span><span>Do achado à peça só sua.</span></div></footer>;}
function ProductCard({product}:{product:Product}) {return <article className="product-card"><Link href={`/produto/${product.slug}`} className="product-picture" aria-label={`Conhecer ${product.name}`}><img src={product.image} alt={`Imagem ${product.gallery ? "REMIX ambientada, edição visual de" : "conceitual de"} ${product.name}; peça física não verificada`} width="640" height="640" loading="lazy"/><Preview>{product.gallery ? "Imagem REMIX · ambientação editada" : "Visualização digital · não é foto de produto físico"}</Preview><span className="product-open"><ArrowUpRight aria-hidden="true" size={20}/></span></Link><div className="product-info"><span className="product-category">{lines.find(line=>line.id===product.line)?.name}</span><Link href={`/produto/${product.slug}`} className="product-name">{product.name}</Link><div className="price-row"><span>{money(product.price)}</span><span>Valor ilustrativo</span></div></div></article>;}
export default function HomeV2(){
  const [active,setActive]=useState('todas');
  const picks=['G-ORG-RC-01','S-HAL-DEC-01','CAN-PET-001','G-CHV-JJ-01'];
  const shown=active==='todas'?picks.map(id=>products.find(product=>product.id===id)).filter((product):product is Product=>Boolean(product)):products.filter(product=>product.line===active);
  return <><Header/><main id="conteudo"><section className="hero container vx-hero"><div className="hero-copy"><h1>Objetos com<br/><span>personalidade.</span></h1><p>Peças para escolher, coleções para celebrar, miniaturas para personalizar e chaveiros para descobrir.</p><div className="hero-buttons"><LinkButton href="/busca">Explorar a vitrine</LinkButton><LinkButton href="/chaveiros" secondary>Descobrir chaveiros</LinkButton></div><div className="hero-footnote"><span className="tiny-mark" aria-hidden="true">+</span> Do projeto à peça. Do achado à peça só sua.</div></div><div className="hero-image"><img src="/images/products/remix/G-VAS-ESC-01_REMIX.webp" alt="Ambientação REMIX editada do SKU G-VAS-ESC-01; peça física não verificada" width="1536" height="1024" fetchPriority="high"/><span className="hero-caption">Design para encontrar<br/>o seu lugar.</span><Preview>Imagem REMIX · ambientação editada</Preview></div></section>
  <section className="lines-section container" aria-labelledby="vx-lines-heading"><div className="section-heading"><h2 id="vx-lines-heading">Quatro caminhos. Uma personalidade.</h2><p>Escolha pelo design, pela ocasião, pela referência pessoal ou pelo contexto.</p></div><div className="line-grid vx-line-grid">{lines.map(line=><Link href={line.path} className={`line-card line-${line.id}`} key={line.id}><div className="line-image"><img src={line.image} width="600" height="420" loading="lazy" alt={`Imagem ${line.id === "feitos" ? "conceitual" : "REMIX ambientada"} da linha ${line.name}; peça física não verificada`}/><Preview>{line.id === "feitos" ? "Imagem conceitual" : "Imagem REMIX · ambientação editada"}</Preview></div><div className="line-card-text"><span className="vx-line-verb">{line.verb}</span><h3>{line.name}<ArrowUpRight aria-hidden="true" size={20}/></h3><p>{line.description}</p></div></Link>)}</div></section>
  <section className="catalog-section container" aria-labelledby="vx-vitrine"><div className="section-heading heading-link"><div><h2 id="vx-vitrine">Encontre um detalhe que combine com você.</h2><p>Uma seleção do catálogo em estudo. Cada peça exige sua própria validação antes da venda.</p></div><Link href="/busca" className="text-link">Conhecer o catálogo<ArrowUpRight aria-hidden="true" size={18}/></Link></div><div className="catalog-toolbar"><div className="filter-chips" role="group" aria-label="Filtrar produtos por linha">{[{id:'todas',name:'Todas'},...lines].map(line=><button key={line.id} type="button" className={active===line.id?'selected':''} aria-pressed={active===line.id} onClick={()=>setActive(line.id)}>{line.name}</button>)}</div><span className="demo-note">Vitrine demonstrativa</span></div><div className="product-grid vx-products">{shown.map(product=><ProductCard product={product} key={product.id}/>)}</div></section>
  <section className="container vx-keyring-feature" aria-labelledby="vx-keyrings"><div className="vx-keyring-photo"><img src="/images/products/remix/G-CHV-JJ-01_REMIX.webp" alt="Ambientação REMIX editada do SKU G-CHV-JJ-01; peça física não verificada" width="800" height="800" loading="lazy"/><Preview>Imagem REMIX · ambientação editada</Preview></div><div className="vx-keyring-copy"><h2 id="vx-keyrings">Pequenos objetos. Novos lugares para descobrir.</h2><p>Chaveiros diversos, articulados e temáticos formam uma linha própria da Vektua XYZ. A seleção pode conversar com o universo de cada comércio, além da experiência digital.</p><p>O modelo de exposição em estabelecimentos locais ainda é uma proposta: não há parceiros, disponibilidade presencial ou condições comerciais confirmados.</p><LinkButton href="/chaveiros">Conhecer a linha Chaveiros</LinkButton><Link href="/contato" className="text-link vx-partner-link">Entenda a proposta para estabelecimentos<ArrowRight aria-hidden="true" size={17}/></Link></div></section>
  <section className="personal-section container"><div className="personal-image"><img src="/images/pet.webp" width="900" height="900" loading="lazy" alt="Ilustração conceitual de miniatura estilizada de pet, não é foto de produto físico"/><Preview/></div><div className="personal-copy"><h2>Aquela companhia.<br/>Agora, em outra forma.</h2><p>Algumas peças a gente escolhe. Outras começam com uma referência que é só nossa.</p><p>Conheça as miniaturas estilizadas de pets e pessoas em estudo, dentro de escopos definidos.</p><LinkButton href="/feitos-para-voce">Explorar personalizados</LinkButton><span className="small-note">Não envie imagens ou dados pessoais neste protótipo.</span></div></section>
  <section className="how-section container"><div className="section-heading"><h2>Clareza faz parte da escolha.</h2><p>Da imagem ao objeto: o que é proposto e o que ainda precisa ser comprovado.</p></div><div className="how-grid"><div><Ruler aria-hidden="true"/><h3>Entenda a peça</h3><p>Medidas, materiais e acabamento devem constar da ficha de cada produto.</p></div><div><Palette aria-hidden="true"/><h3>Conheça as opções</h3><p>Cor, variante e personalização só estarão disponíveis após especificação e testes.</p></div><div><Box aria-hidden="true"/><h3>Saiba o que esperar</h3><p>Preço, prazo e disponibilidade dependem de validação individual e autorização.</p></div></div><Link href="/como-funciona" className="text-link">Como funciona a experiência<ArrowRight aria-hidden="true" size={18}/></Link></section></main><Footer/></>;
}
