/** Internal portfolio snapshot from Founder decision DEC-009 (2026-09-19).
 * Inclusion is not a SKU release, license finding, verified price or permission to sell.
 */
export type Line = 'objetos' | 'datas' | 'feitos';
export type Product = {
  id: string; slug: string; name: string; line: Line; kind: string; price: number;
  image: string; imagePosition?: string; description: string; dimensions: string;
  includes: string; colors: string[]; demo: true; statusGate: 'EVIDENCE_PENDING';
  imageNature: 'render-digital' | 'illustration'; imageNotice: string;
  source3mf?: string; sourceDriveId?: string; imageSource?: string;
};
export const lines = [
  { id:'objetos' as const, name:'Objetos & Colecionáveis', path:'/objetos-colecionaveis', verb:'Para escolher', description:'Peças selecionadas para organizar, decorar e expressar interesses. Produtos em validação.', image:'/images/products/G-ORG-RC-01-main.webp' },
  { id:'datas' as const, name:'Datas & Coleções', path:'/datas-colecoes', verb:'Para celebrar', description:'Modelos de Halloween e Natal em preparação. Nenhuma venda ou prazo está autorizado.', image:'/images/products/S-HAL-DEC-01-main.webp' },
  { id:'feitos' as const, name:'Feitos para Você', path:'/feitos-para-voce', verb:'Para personalizar', description:'Estudos de miniaturas estilizadas de pessoas e pets via Hi3D, sem pedido ou fotos reais.', image:'/images/pet.webp' },
];
const fixture={demo:true as const,statusGate:'EVIDENCE_PENDING' as const};
const renderNotice='Render digital derivado da geometria do arquivo 3D; não é fotografia. Produto físico sujeito à validação.';
const illustrativeNotice='Ilustração demonstrativa. Não existe foto nem modelo estático validado desta oferta.';
const renders='/images/products/';
// Valores numéricos abaixo são exclusivamente fixtures necessárias ao carrinho DEMO existente;
// NÃO são preços propostos, aprovados ou habilitados para cobrança.
export const products:Product[]=[
  {...fixture,id:'G-ORG-RC-01',slug:'organizador-controles-remotos',name:'Organizador para controles remotos',line:'objetos',kind:'Organização',price:49,image:`${renders}G-ORG-RC-01-main.webp`,imageNature:'render-digital',imageNotice:renderNotice,source3mf:'G-ORG-RC-01.3mf',sourceDriveId:'1l4VXpv5eZOZCzrrYTM4JB4DLq7P8OlAD',description:'Modelo selecionado para apoiar controles remotos sobre uma superfície. Não é a versão de parede. Fixação, acabamento, capacidade e desempenho ainda dependem de teste físico.',dimensions:'A confirmar por ficha e protótipo.',includes:'Conceito de 1 organizador; conteúdo final a confirmar.',colors:['Cor a definir']},
  {...fixture,id:'G-VAS-ESC-01',slug:'cachepot-escultorico',name:'Cachepot escultórico',line:'objetos',kind:'Decoração',price:89,image:`${renders}G-VAS-ESC-01-main.webp`,imageNature:'render-digital',imageNotice:renderNotice,source3mf:'G-VAS-ESC-01.3mf',sourceDriveId:'1CvbfEaEGEpTRuEeJkIZCO-oiIqx_zPHb',description:'Modelo escultórico de terceiro selecionado para estudo. A criação autoral da Vektua XYZ não está comprovada; licença, função como cachepot e uso com água permanecem em análise.',dimensions:'A confirmar por ficha e protótipo.',includes:'Conceito de 1 peça decorativa; composição final a validar.',colors:['Cor a definir']},
  {...fixture,id:'G-VAS-MIN-01',slug:'kit-mini-cachepots',name:'Kit de três mini-cachepots decorativos',line:'objetos',kind:'Decoração',price:79,image:`${renders}G-VAS-MIN-01-main.webp`,imageNature:'render-digital',imageNotice:'Render do arquivo 3D, que contém quatro geometrias. Seleção das três peças do kit e função ainda não validadas. Não é foto física.',source3mf:'G-VAS-MIN-01.3mf',sourceDriveId:'1jk6e35ESsyaKm6EJxlmzeAOqYk4QI929',description:'Proposta de kit com três peças. O 3MF encontrado contém quatro objetos e ainda é necessário definir quais três compõem a oferta. Uso com plantas, drenagem e contato com água não validados.',dimensions:'A confirmar por peça.',includes:'Proposta de 3 unidades; escolha dos três modelos pendente.',colors:['Cores a definir']},
  {...fixture,id:'G-ORG-HS-01',slug:'suporte-headset',name:'Suporte para headset sem adesivo',line:'objetos',kind:'Organização',price:69,image:`${renders}G-ORG-HS-01-main.webp`,imageNature:'render-digital',imageNotice:renderNotice,source3mf:'G-ORG-HS-01.3mf',sourceDriveId:'16-7NGx_JZd0xRNQ8zU1fYqNBephgLwqT',description:'Suporte de apoio para headset, sem fixação adesiva prevista. Equilíbrio, carga e compatibilidade ainda não foram testados.',dimensions:'A confirmar.',includes:'Conceito de 1 suporte; headset não incluído.',colors:['Cor a definir']},
  {...fixture,id:'G-CHV-JJ-01',slug:'chaveiro-faixa-jiu-jitsu',name:'Chaveiro em formato de faixa de jiu-jítsu',line:'objetos',kind:'Chaveiros',price:29,image:`${renders}G-CHV-JJ-01-main.webp`,imageNature:'render-digital',imageNotice:'Visualização derivada do layout multipeças do arquivo 3MF, não de uma unidade final montada. Foto física pendente.',source3mf:'G-CHV-JJ-01.3mf',sourceDriveId:'1qFG7xHHpnMOc2D0kcbI18343Ctwt-iCZ',description:'Conceito de chaveiro inspirado em faixa de jiu-jítsu. O modelo fonte reúne opções/partes; montagem, escolha de cores, resistência e destinação devem ser validadas.',dimensions:'A confirmar.',includes:'Proposta de 1 chaveiro após definição de montagem.',colors:['Combinação a definir']},
  {...fixture,id:'S-HAL-DEC-01',slug:'abobora-halloween',name:'Decoração de Halloween — abóbora',line:'datas',kind:'Halloween',price:89,image:`${renders}S-HAL-DEC-01-main.webp`,imageNature:'render-digital',imageNotice:renderNotice,source3mf:'S-HAL-DEC-01.3mf',sourceDriveId:'1CeAHWhzmG0DzwzvE9H0SRLz-A5uKeGdL',description:'Abóbora decorativa baseada em arquivo apresentado como porta-doces. Cadeia de licença do remix, segurança e adequação a contato com alimentos não verificadas.',dimensions:'A confirmar.',includes:'Conceito de 1 abóbora; itens cenográficos não incluídos.',colors:['Cor a definir']},
  {...fixture,id:'S-NAT-PRE-01',slug:'presepio-minimalista',name:'Presépio minimalista de Natal',line:'datas',kind:'Natal',price:119,image:`${renders}S-NAT-PRE-01-main.webp`,imageNature:'render-digital',imageNotice:'Visualização preliminar de malha 3D de alta densidade; não é foto física. Quantidade de peças não confirmada.',source3mf:'S-NAT-PRE-01.3mf',sourceDriveId:'1zjnsfdA-S9PdhP8XD6WiGh3aZWMzIMWT',description:'Composição natalina minimalista em avaliação. O arquivo precisa de conferência de partes e montagem; não há comprovação de peça única.',dimensions:'A confirmar.',includes:'Composição/quantidade final de peças a confirmar.',colors:['Cor a definir']},
  {...fixture,id:'CAN-PESSOA-001',slug:'miniatura-pessoa',name:'Miniatura caricata estilizada de pessoa',line:'feitos',kind:'Personalizados',price:299,image:`${renders}CAN-PESSOA-001-placeholder.svg`,imageNature:'illustration',imageNotice:illustrativeNotice,description:'Oferta-base de modelagem via Hi3D em estudo. Não há modelo estático de referência localizado; resultado, consentimentos, licença de outputs, revisões e prazo precisam de validação.',dimensions:'A definir por especificação.',includes:'Oferta de estudo; escopo de produção e revisões não aprovado.',colors:['Conforme escopo futuro']},
  {...fixture,id:'CAN-PET-001',slug:'miniatura-pet',name:'Miniatura estilizada de pet',line:'feitos',kind:'Personalizados',price:249,image:`${renders}CAN-PET-001-placeholder.svg`,imageNature:'illustration',imageNotice:illustrativeNotice,description:'Oferta-base de modelagem via Hi3D em estudo. Sem promessa de reprodução fotorrealista, prazo fixo ou revisões ilimitadas; uso de fotos e direitos dos outputs dependem de verificação.',dimensions:'A definir por especificação.',includes:'Oferta de estudo; escopo de produção e revisões não aprovado.',colors:['Conforme escopo futuro']},
];
export const money=(value:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
export const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function filterProducts(items:Product[],query:string,category:string,sort:string){
 const terms=normalize(query).trim().split(/\s+/).filter(Boolean);
 return items.filter(p=>terms.every(term=>normalize(`${p.id} ${p.name} ${p.description} ${p.kind} ${lines.find(l=>l.id===p.line)?.name}`).includes(term))&&(category==='Todos'||p.kind===category)).sort((a,b)=>sort==='price-asc'?a.price-b.price:sort==='price-desc'?b.price-a.price:0);
}
export const faq=[
 ['O site já está vendendo?', 'Não. Este é um ambiente demonstrativo; composição de portfólio não equivale à autorização de venda. Preços são fictícios, sem pagamento nem pedido.'],
 ['As imagens mostram peças impressas?', 'Imagens dos sete modelos de catálogo são renders digitais de arquivos 3MF, não fotografias. As duas ofertas Hi3D têm apenas ilustrações de ausência de amostra.'],
 ['A miniatura fica idêntica à fotografia?', 'Não há promessa de fotorrealismo. Estilo e resultados precisam de provas e aprovação de escopo antes de qualquer encomenda.'],
 ['Posso escolher cores e tamanhos?', 'Os seletores são somente ilustrativos. Materiais, dimensões, cores, revisões e montagem exigem ficha e testes.'],
 ['Quando começa a produção?', 'Nenhuma produção é iniciada pelo protótipo. Direitos, testes, preço, capacidade e autorização de comercialização ainda estão pendentes.'],
 ['Posso enviar fotos de pessoas ou pets?', 'Não. O upload de imagens pessoais está desativado e depende de política de privacidade e termos Hi3D verificados.'],
];