export type Line = 'objetos' | 'datas' | 'feitos';
export type Product = {
  id: string; slug: string; name: string; line: Line; kind: string; price: number;
  image: string; imagePosition?: string; description: string; dimensions: string;
  includes: string; colors: string[]; demo: true; statusGate: 'EVIDENCE_PENDING';
};

// DEC-009 (19/09/2026) approves portfolio COMPOSITION only, not individual SKU release.
// All prices are strictly interface fixtures; no purchase, checkout, stock or promises are enabled.
export const lines = [
  { id: 'objetos' as const, name: 'Objetos & Colecionáveis', path: '/objetos-colecionaveis', verb: 'Para escolher', description: 'Peças interessantes para usar, exibir ou presentear.', image: '/images/products/G-ORG-RC-01-main.svg' },
  { id: 'datas' as const, name: 'Datas & Coleções', path: '/datas-colecoes', verb: 'Para celebrar', description: 'Objetos e coleções pensados para diferentes ocasiões.', image: '/images/products/S-HAL-DEC-01-main.svg' },
  { id: 'feitos' as const, name: 'Feitos para Você', path: '/feitos-para-voce', verb: 'Para personalizar', description: 'Miniaturas estilizadas: escopo, amostras e condições ainda em validação.', image: '/images/pet.webp' },
];
const fixture = { demo: true as const, statusGate: 'EVIDENCE_PENDING' as const };
const renderNotice = 'Visualização digital derivada da geometria do arquivo 3MF original; não é fotografia de peça fabricada. Direitos do modelo, fabricação, medidas, cor, segurança, preço e liberação comercial ainda sujeitos à validação.';
const hi3dNotice = 'Oferta em estudo via Hi3D. Imagem de exemplo meramente ilustrativa, não fotografia de produto fabricado. Não envie fotos nem dados pessoais: o recebimento e o tratamento dependem de condições, privacidade e testes aprovados.';
export const products: Product[] = [
  { ...fixture, id:'G-ORG-RC-01', slug:'g-org-rc-01', name:'Organizador para controles remotos — de apoio, não de parede', line:'objetos', kind:'Organização', price:79, image:'/images/products/G-ORG-RC-01-main.svg', description:'Organizador de apoio para controles remotos, versão expressamente escolhida como NÃO de parede pelo Founder em 19/09/2026. A geometria encontrada no 3MF tem compartimentos e base de apoio. '+renderNotice, dimensions:'Medidas finais pendentes de ficha técnica e protótipo.', includes:'1 organizador, proposta de unidade ainda não liberada. Controles não incluídos.', colors:['A validar'] },
  { ...fixture, id:'S-HAL-DEC-01', slug:'s-hal-dec-01', name:'Decoração de Halloween — abóbora porta-doces', line:'datas', kind:'Halloween', price:89, image:'/images/products/S-HAL-DEC-01-main.svg', description:'Abóbora decorativa porta-doces representada pelo arquivo 3MF escolhido. Direitos do remix e do modelo original, segurança e uso pretendido pendentes de revisão. '+renderNotice, dimensions:'A confirmar a partir do projeto e protótipo.', includes:'Conteúdo e quantidade de peças a confirmar. Doces e itens cenográficos não incluídos.', colors:['A validar'] },
  { ...fixture, id:'CAN-PET-001', slug:'can-pet-001', name:'Miniatura estilizada de pet — estudo de personalização', line:'feitos', kind:'Personalizados', price:249, image:'/images/pet.webp', description:'Proposta de miniatura estilizada de pet desenvolvida a partir de referências, condicionada a testes de geração Hi3D, direitos dos outputs, privacidade, escopo e viabilidade da impressão. Não é reprodução fotográfica. '+hi3dNotice, dimensions:'Dimensões a especificar e validar.', includes:'Escopo, revisão, referência, acabamento e unidade de venda a especificar.', colors:['A definir por oferta validada'] },
  { ...fixture, id:'G-VAS-ESC-01', slug:'g-vas-esc-01', name:'Cachepot escultórico — modelo de terceiro, conceito em análise', line:'objetos', kind:'Decoração', price:89, image:'/images/products/G-VAS-ESC-01-main.svg', description:'Estudo de cachepot escultórico com geometria de modelo identificado como criação de terceiro. Não se declara design original Vektua XYZ. Licença e direitos da imagem e do modelo ainda exigem parecer específico; função de cachepot deve ser validada. '+renderNotice, dimensions:'A confirmar; geometria não equivale à prova de funcionalidade.', includes:'Composição e itens incluídos sujeitos a definição. Planta não incluída.', colors:['A validar'] },
  { ...fixture, id:'G-VAS-MIN-01', slug:'g-vas-min-01', name:'Kit de três mini-cachepots decorativos — função a validar', line:'objetos', kind:'Decoração', price:99, image:'/images/products/G-VAS-MIN-01-main.svg', description:'Kit previsto de três mini-cachepots, com quantidade de componentes, estabilidade, função de vaso e características finais pendentes de reconciliação do 3MF e teste físico. '+renderNotice, dimensions:'A confirmar individualmente por componente.', includes:'Oferta pretendida: três mini-cachepots. Composição efetiva do arquivo e unidade final a validar; plantas não incluídas.', colors:['A validar'] },
  { ...fixture, id:'G-ORG-HS-01', slug:'g-org-hs-01', name:'Suporte para headset — sem fixação adesiva', line:'objetos', kind:'Organização', price:69, image:'/images/products/G-ORG-HS-01-main.svg', description:'Suporte de apoio para headset, sem fixação adesiva. Estabilidade, compatibilidade e direitos do arquivo dependem de verificação. '+renderNotice, dimensions:'A confirmar na ficha e em protótipo.', includes:'1 suporte proposto; headset não incluído.', colors:['A validar'] },
  { ...fixture, id:'G-CHV-JJ-01', slug:'g-chv-jj-01', name:'Chaveiro em formato de faixa de jiu-jítsu', line:'objetos', kind:'Chaveiros', price:29, image:'/images/products/G-CHV-JJ-01-main.svg', description:'Estudo de chaveiro em forma de faixa de jiu-jítsu. O 3MF contém múltiplos componentes e variantes; combinação, cor e montagem definitivas ainda precisam de seleção e testes. '+renderNotice, dimensions:'A confirmar para a variante selecionada.', includes:'1 chaveiro proposto; argola, cores e acessórios ainda não especificados.', colors:['A validar'] },
  { ...fixture, id:'S-NAT-PRE-01', slug:'s-nat-pre-01', name:'Presépio minimalista de Natal', line:'datas', kind:'Natal', price:89, image:'/images/products/S-NAT-PRE-01-main.svg', description:'Conjunto natalino minimalista representado pela geometria do 3MF localizado. A quantidade de peças e a arquitetura do modelo ainda precisam ser verificadas; não há afirmação de peça única. '+renderNotice, dimensions:'A confirmar na ficha e nos testes.', includes:'Composição a confirmar após identificação de componentes reais.', colors:['A validar'] },
  { ...fixture, id:'CAN-PESSOA-001', slug:'can-pessoa-001', name:'Miniatura caricata estilizada de pessoa — estudo Hi3D', line:'feitos', kind:'Personalizados', price:249, image:'/images/person.webp', description:'Estudo de miniatura caricata estilizada de pessoa via Hi3D. Não promete semelhança exata, prazo fixo ou revisões ilimitadas. Exemplos e condições de privacidade e direitos ainda exigem validação. '+hi3dNotice, dimensions:'Dimensões ainda não validadas.', includes:'Escopo de referência, revisão, prévia e aprovação a especificar.', colors:['A definir por oferta validada'] },
];
export const money = (value:number) => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(value);
export const normalize = (value:string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
export function filterProducts(items: Product[], query:string, category:string, sort:string) {
  const terms = normalize(query).trim().split(/\s+/).filter(Boolean);
  return items.filter(p => terms.every(term => normalize(`${p.id} ${p.name} ${p.description} ${p.kind} ${lines.find(l=>l.id===p.line)?.name}`).includes(term)) && (category==='Todos' || p.kind===category)).sort((a,b)=>sort==='price-asc'?a.price-b.price:sort==='price-desc'?b.price-a.price:0);
}
export const faq = [
  ['O que posso explorar neste site?', 'Você pode conhecer as três linhas, filtrar peças, abrir fichas e experimentar o carrinho e a personalização em modo demonstrativo. Os nove SKUs correspondem à composição DEC-009, não estão liberados para venda; todos os valores são fictícios e não há pagamento habilitado.'],
  ['As imagens são fotografias de peças prontas?', 'Não. As imagens identificadas como geometria 3MF são visualizações digitais derivadas dos modelos recebidos. Fotos reais, direitos de uso e protótipos precisam de verificação. Imagens das duas ofertas personalizadas são somente exemplos ilustrativos.'],
  ['A miniatura fica idêntica à fotografia?', 'Não há promessa de fotorrealismo. A proposta ainda em estudo é uma interpretação estilizada; características e limites precisam de aprovação antes de qualquer oferta.'],
  ['Posso escolher as cores?', 'Os seletores exibidos são demonstrativos. Cores e variantes reais dependem da especificação e da validação técnica de cada SKU.'],
  ['Quando começa a produção?', 'Este site não inicia fabricação, aceita pedidos ou realiza pagamentos. Protótipos e vendas dependem de direitos, testes e decisões específicas do Founder.'],
  ['Como funcionam entrega e devoluções?', 'As condições comerciais ainda estão em preparação; não há frete, estoque nem prazo confirmado.'],
  ['Posso enviar uma foto do meu pet ou de outra pessoa?', 'Não envie referências pessoais neste protótipo. O processo de recebimento depende de fluxo privado, termos e privacidade verificados.'],
];
